@isTest
private class BatchJob_Test {
	
	//static testMethod void batchStatusBarTest(){    
 //       list<Account> accts  new list<Account>();
 //       for(integer i=0;i<(math.round(math.random()*200)+1);i++)
 //           accts.add(new Account(Name='test'+string.valueof(i)));
 //       insert accts;

 //       id batchInstance=database.executeBatch(new test_Batch());

 //       test.startTest();

 //       batchJobs controller = new batchJobs();
 //       controller.getBatchJobs();
 //       id batchInstance2=database.executeBatch(new test_Batch());
 //       controller.getBatchJobs();

 //       test.stopTest();
 //   }
	
}